#!/system/bin/sh
export PATH=/system/bin:/sbin:$PATH
SRC=/system/bootstrap/
BB=/system/xbin/busybox
AWK="$BB awk"

$BB mount -o remount,rw rootfs /

# copy busybox
$BB cp $BB /sbin
# minimal symlinks
$BB ln -s $BB /sbin/cp
$BB ln -s $BB /sbin/[

# touch stamp to prevent loop execution
$BB touch /.bootstamp

#
# check mode
#

key=
if $BB [ -e /system/bootstrap/getkey ]; then
  key=$(/system/bootstrap/getkey)
fi

#
# volume up - original firmware mode
#
if $BB [ ! -z "$key" ] && $BB [ "$key" = 115 ]; then
  exit 0
fi

TYPE=normal
if $BB [ -f /cache/.recovery_mode ] || $BB [ "$key" = 114 ]; then
  TYPE=recovery
fi

# remove symbolic links
$BB rm sdcard

#
# remove lg crap
#
$BB rm /*.rc
$BB rm /*.sh

#
# volume down - recovery mode
#
if $BB [ "$TYPE" = "recovery" ]; then
  # unlink /etc
  $BB rm /etc
  $BB mkdir /etc

  $BB cp -fr /system/bootstrap/recovery.tar /
  $BB tar xf /recovery.tar

  if [ ! -z "$restart_adb" ]; then
    $BB killall adbd
  fi
  $BB killall ueventd
  
  $BB mkdir /tmp
  $BB mkdir /sdcard
  $BB chmod 666 /dev/graphics/fb*

  $BB mount -o remount,rw /system /system

  # remove /cache/.recovery_mode
  $BB rm /cache/.recovery_mode
#
# normal mode
#
else
  $BB cp -fr /system/bootstrap/boot.tar /
  $BB tar xf /boot.tar

  $BB killall ueventd
fi

# unmount stuff
$BB umount /dev/cpuctl
$BB umount /dev/pts
$BB umount /data
$BB umount /dvp
$BB umount /persist
$BB umount /sys/kernel/debug
$BB umount /system/app
$BB umount /mpt
$BB umount /mnt/asec
$BB umount /mnt/obb
$BB umount /mnt/extasec
$BB umount /mnt/extobb

# set our init only to the first core << check this
/system/bootstrap/taskset -p -c 0 1
/system/bootstrap/taskset -c 0 /system/bootstrap/2nd-init
#/system/bootstrap/2nd-init

exit 0
